### ISSUE TITLE
Repeat.for inserts empty elements

### ISSUE THREAD

**Issue by pkkummermo** [aurelia/templating#580] opened 2017-11-14 08:01 UTC
**I'm submitting a bug report**

* **Library Version:**
"aurelia-templating": "1.6.0",
"aurelia-templating-binding": "1.4.0",
"aurelia-templating-resources": "1.5.4",
"aurelia-templating-router": "1.2.0"

**Please tell us about your environment:**
* **Operating System:**
Ubuntu Linux

* **Node Version:**
8.9.1

* **NPM Version:**
5.5.1

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17
webpack

* **Browser:**
all

* **Language:**
TypeScript 2.5.2

**Current behavior:**
Repeat inserts empty elements. Context is inside a modal if it matters.

![image](https://user-images.githubusercontent.com/1799456/32768810-b80a3334-c919-11e7-9ac2-f0357fa3c54f.png)

EventLog.html
```
<pre class="event-log__entry" repeat.for="message of websocketData">
      #${ $index } - ${ message }
    </pre>
```

**Expected/desired behavior:**

Reverting back to makes the issue go away.

"aurelia-templating": "1.4.2",
"aurelia-templating-binding": "1.3.0",
"aurelia-templating-resources": "1.4.0",
"aurelia-templating-router": "1.1.0"

![image](https://user-images.githubusercontent.com/1799456/32768898-068c6d60-c91a-11e7-9692-ac49e53bf008.png)

* **What is the expected behavior?**
No ghost elements in the repeat.

* **What is the motivation / use case for changing the behavior?**
Awesome iterations.

**Comment by StrahilKazlachev** [comment] 2017-11-14 08:25
Looks like duplicate of aurelia/framework#830.

**Comment by pkkummermo** [comment] 2017-11-14 08:34
Very likely!

**Comment by bigopon** [comment] 2017-11-14 09:27
@pkkummermo Do you have an if outside of `<event-log/>` ?

**Comment by pkkummermo** [comment] 2017-11-14 13:26
Nope! The whole template is:

```
<template>
  <require from="./event-log.scss"></require>
  <div class="event-log">
    <pre class="event-log__entry" repeat.for="message of websocketData">
      #${ $index } - ${ message }
    </pre>
  </div>
</template>
```

which is required in EventLogDialog.html
```
<template>
  <require from="components/common/event-log/event-log"></require>
  <div class="modal">
    <div class="flex-container">
      <div class="flex-container__header">
        <h2 class="h2">Event log</h2>
      </div>
      <div class="flex-container__body flex-container__body--scroll">
        <event-log event-log-stream-endpoint.bind="eventLogStreamEndpoint"></event-log>
      </div>
      <div class="flex-container__footer">
        <button class="button button--primary" type="submit" click.delegate="close()">Close event log</button>
      </div>
    </div>
  </div>
</template>
```

HOWEVER it's inside a modal (https://github.com/aurelia/dialog), which might do some if-handling that I do not know of.

**Comment by StrahilKazlachev** [comment] 2017-11-14 13:51
The only `if`s I can remember of, are for some buttons in the *header* and *footer*. User content is not *injectable* there.

**Comment by bigopon** [comment] 2017-11-14 21:53
Can you help put the repeat inside a normal element instead of dialog, using the latest version to see if it also goes wrong ?

**Comment by StrahilKazlachev** [comment] 2017-11-14 22:16
@pkkummermo I still haven't seen how the array is modified. So if you are using `.push`, `.splice`, ... the simplest test to see if the issue is the same *should* be to *replace* the array *instead* of modifying it.

**Comment by pkkummermo** [comment] 2017-11-15 06:28
```
  onMessage(message: any) {
    Log.debug("Got message", message);
    this.websocketData.push(message.data);
  }
```
@StrahilKazlachev super simple push upon new data from WebSocket.

@bigopon I'll try it after my morning coffee injection :)

**Comment by pkkummermo** [comment] 2017-11-15 10:01
Ok, the issue actually persists _outside_ the dialog as well. I'll try to further isolate what causes it.

**Comment by pkkummermo** [comment] 2017-11-15 10:07
All right, error isolated!

```
  initiateWebsocket() {
    Log.debug("Initiating websocket");
    this.websocketData.push("Connecting to endpoint");
    this.websocket = new Websocket({
      url: this.aureliaConfiguration.get("api.wsEndpoint") + this.eventLogStreamEndpoint,
      onmessage: (message) => { this.onMessage(message); },
      onopen: () => { this.websocketData.push("Connected to endpoint, awaiting data"); },
      onerror: () => { this.websocketData.push("There was an error connecting to the endpoint"); },
      onclose: () => { this.websocketData.push("Websocket was closed"); },
    });
  }
```

If i comment out the `this.websocket = new Websocket...` there's no duplicates. Is there a race condition in terms of the native WebSocket implementation which interferes with the internal task system?

**Comment by bigopon** [comment] 2017-11-15 10:13
I think you are running into the same issue with the linked issue. Can you give the work around a try ?

**Comment by pkkummermo** [comment] 2017-11-15 13:10
SetTimeout? That ain't going to fly. I'd rather roll back the update then.

**Comment by StrahilKazlachev** [comment] 2017-11-15 13:35
@pkkummermo Did you try what I previously suggested, not mutating the array, but replacing it with new one? In the case with `.push` you can do `this.websocketData = [...this.websocketData, message.data];`.

**Comment by pkkummermo** [comment] 2017-11-15 15:34
@StrahilKazlachev That worked :) This can be a temp workaround untill it gets fixed in a patch later on. Thanks! Should I just let the issue stay open and add solution to the top?

**Comment by StrahilKazlachev** [comment] 2017-11-15 15:35
I've mentioned this in the other issue. We are tracking it there.

**Closed** 2017-11-15 15:37 UTC
