### ISSUE TITLE
"this.animator.enter is undefined" error

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/templating#273] opened 2016-02-22 17:40 UTC
If an element has an `au-animate` class on it but no animator is present, we get a typeError  in the console when templating calls `this.animator.enter` as `this.animator` is not defined.

Proposing a default animator class or interface with all methods as no-ops to mitigate this issue. Developers may choose to swap animators or disable the animator dynamically, and so there should be a logical fallback. If the no-op methods use `Function.prototype` as the call (instead of, say, an empty function) they should have no overhead.

**Comment by EisenbergEffect** [comment] 2016-02-22 18:02
That should be implemented already....are you sure something isn't going wrong with your app?

**Comment by jedd-ahyoung** [comment] 2016-02-22 19:48
I'll double-check the dependencies, but I should be fairly up-to-date. I'm
seeing this on an element with an `au-animate` class and a `show.bind`. I
was using the animator-css plugin and am no longer using it (it's commented
out in the configure method) but I did not remove the au-animate classes
and it's still in the systemJS configuration.

JSPM inspect is as follows:

```
PS C:\Projects\FREDMS\Source\Edms.Client\DashboardMVC> jspm inspect
     Installed Versions

                    github:aurelia/logging 0.7.0
                        github:aurelia/pal 0.1.10
                github:aurelia/pal-browser 0.1.13
                  github:components/jquery 2.1.4
                       github:github/fetch 0.9.0
                github:jedd-ahyoung/dialog temp-release
       github:jedd-ahyoung/logging-network 0.0.2
               github:jspm/nodelibs-assert 0.1.0
               github:jspm/nodelibs-buffer 0.1.0
        github:jspm/nodelibs-child_process 0.1.0
               github:jspm/nodelibs-events 0.1.1
                   github:jspm/nodelibs-fs 0.1.2
                 github:jspm/nodelibs-http 1.7.1
                github:jspm/nodelibs-https 0.1.0
               github:jspm/nodelibs-module 0.1.0
                   github:jspm/nodelibs-os 0.1.0
                 github:jspm/nodelibs-path 0.1.0
              github:jspm/nodelibs-process 0.1.2
               github:jspm/nodelibs-stream 0.1.0
                  github:jspm/nodelibs-url 0.1.0
                 github:jspm/nodelibs-util 0.1.0
                 github:rstacruz/nprogress 0.2.0
                github:systemjs/plugin-css 0.1.16 0.1.20
               github:systemjs/plugin-json 0.1.0
               github:systemjs/plugin-text 0.0.2
                     github:twbs/bootstrap 3.3.5
                                npm:Base64 0.2.1
                              npm:amdefine 1.0.0
                                npm:assert 1.3.0
                  npm:aurelia-animator-css 1.0.0-beta.1.0.2
                         npm:aurelia-async 0.6.1
                       npm:aurelia-binding 1.0.0-beta.1.1.1
                  npm:aurelia-bootstrapper 1.0.0-beta.1
          npm:aurelia-dependency-injection 1.0.0-beta.1
              npm:aurelia-event-aggregator 1.0.0-beta.1
                  npm:aurelia-fetch-client 1.0.0-beta.1.0.2
                     npm:aurelia-framework 1.0.0-beta.1.0.7
                       npm:aurelia-history 1.0.0-beta.1
               npm:aurelia-history-browser 1.0.0-beta.1.0.1
                   npm:aurelia-http-client 1.0.0-beta.1
                        npm:aurelia-loader 1.0.0-beta.1
                npm:aurelia-loader-default 1.0.0-beta.1.0.1
                       npm:aurelia-logging 1.0.0-beta.1.1.1
               npm:aurelia-logging-console 1.0.0-beta.1 1.0.0-beta.1.1.3
                      npm:aurelia-metadata 1.0.0-beta.1.1.3
                           npm:aurelia-pal 1.0.0-beta.1.1.1
                   npm:aurelia-pal-browser 1.0.0-beta.1.0.1
                          npm:aurelia-path 1.0.0-beta.1
              npm:aurelia-route-recognizer 1.0.0-beta.1
                        npm:aurelia-router 1.0.0-beta.1
                    npm:aurelia-task-queue 1.0.0-beta.1.1.0
                    npm:aurelia-templating 1.0.0-beta.1.0.2
            npm:aurelia-templating-binding 1.0.0-beta.1.0.2
          npm:aurelia-templating-resources 1.0.0-beta.1.0.3
             npm:aurelia-templating-router 1.0.0-beta.1.0.4
                            npm:babel-core 5.8.25
                         npm:babel-runtime 5.8.25
                             npm:base64-js 0.0.8
                                npm:buffer 3.6.0
                             npm:clean-css 3.4.9
                             npm:commander 2.8.1
                               npm:core-js 1.2.1 1.2.6 2.0.3
                          npm:core-util-is 1.0.2
                                npm:events 1.0.2
                          npm:font-awesome 4.4.0
                     npm:graceful-readlink 1.0.1
                      npm:https-browserify 0.0.0
                               npm:ieee754 1.1.6
                              npm:inherits 2.0.1
                               npm:isarray 0.0.1 1.0.0
                                npm:jquery 2.2.0
                                npm:moment 2.11.2
                               npm:numeral 1.5.3
                         npm:os-browserify 0.1.2
                       npm:path-browserify 0.0.0
                               npm:process 0.11.2
                              npm:punycode 1.3.2
                           npm:querystring 0.2.0
                       npm:readable-stream 1.1.13
                            npm:source-map 0.4.4
                     npm:stream-browserify 1.0.0
                        npm:string_decoder 0.10.31
                                   npm:url 0.10.3
                                  npm:util 0.10.3
```

2016-02-22 13:03 GMT-05:00 Rob Eisenberg <notifications@github.com>:

**Comment by EisenbergEffect** [comment] 2016-02-22 19:51
The default implemenation of Animator with noop methods is inside of Templating and is what gets used by default. For example, the skeleton-navigation app is configured with au-animate classes on its views but the css-animator is commented out…and it works fine. There’s got to be something else happening in your case.

**Comment by jedd-ahyoung** [comment] 2016-02-22 20:56
I'll have to look into this more. It looks as though the animator is
defined for some viewSlots but not for the children? I'll try to see if I
can reproduce a test case, but it might take a bit as I've got some things
on my plate.

2016-02-22 14:51 GMT-05:00 Rob Eisenberg <notifications@github.com>:

**Comment by EisenbergEffect** [comment] 2016-07-04 14:45
Closing this since I could not reproduce or see how there could ever be a null animator.

**Closed by EisenbergEffect** 2016-07-04 14:45 UTC
