### ISSUE TITLE
autoplayed HTML5 Video has 2 instances in aurelia and no way to stop the presumably cached instance

### ISSUE THREAD

**Issue by doodlesbykumbi** [aurelia/templating#355] opened 2016-05-19 14:16 UTC
Spotted a bug, autoplayed HTML5 Video has 2 instances in aurelia - you stop the one in the DOM and the one presumably cached keeps on playing. Here is a gist showing what-I’m-a-talking-about https://gist.run/?id=9f2bb607dab678ffe7e4029b72a9059f

**Comment by EisenbergEffect** [comment] 2016-05-19 15:04
@jdanyow Can you look into this?

**Comment by atsu85** [comment] 2016-05-19 16:03
I found a workaround, that includes binding autoplay to VM property:
https://gist.run/?id=59b857965146f0a2abfb5fa1bc4bddb1

**Comment by jdanyow** [comment] 2016-05-19 16:40
changing:

```html
<video src="http://video.webmfiles.org/big-buck-bunny_trailer.webm"
            ref="player" loop controls autoplay>
</video>
```

to this:

```html
<video src.bind="'http://video.webmfiles.org/big-buck-bunny_trailer.webm'"
            ref="player" loop controls autoplay>
</video>
```
also fixes it.  https://gist.run/?id=53aac3b5becc5ca8703187e09093176a

Will need to look into this more but I'm guessing the instance owned by the view-factory is playing.

**Comment by jdanyow** [comment] 2016-06-02 02:12
@EisenbergEffect it's caused by this line:  https://github.com/aurelia/templating/blob/1.0.0-beta.2.0.1/src/view-compiler.js#L118

here's a simple html page that reproduces the issue:

https://gist.run/?id=cb657718c3b6b34c043b34f3356d5a84
```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>GistRun</title>
</head>
<body>
  <template>
    <video src="http://video.webmfiles.org/big-buck-bunny_trailer.webm"
           loop controls autoplay>
    </video>
  </template>
  <script>
    let template = document.querySelector('template');
    document.adoptNode(template.content);
  </script>
</body>
</html>
```

**Comment by EisenbergEffect** [comment] 2016-06-02 02:20
That seems like a bug in the browsers doesn't it? Could we switch to importNode? https://developer.mozilla.org/en-US/docs/Web/API/Document/importNode

**Comment by jdanyow** [comment] 2016-06-02 03:02
`importNode` seems to fix it although it comes at a cost.  I've posted a question on stackoverflow to try and find out if this is a browser bug.  http://stackoverflow.com/questions/37581912/should-a-video-that-is-not-attached-to-the-dom-autoplay

seems like `adoptNode` and `importNode` should have the same behavior in this regard.

**Comment by EisenbergEffect** [comment] 2016-06-02 03:03
Is it a performance hit?

**Comment by jdanyow** [comment] 2016-06-02 03:22
I assumed it would be because it clones the node but maybe not:  https://gist.run/?id=daffcecb9d59e66bb67bb0a0ba3e163a

**Comment by EisenbergEffect** [comment] 2016-07-07 14:58
Ok, finally checked out the gist. On my Chrome instance, the importNode was actually faster. @jdanyow What do you think? Should I switch the api call? Any negative side-effects of that?

**Comment by EisenbergEffect** [comment] 2016-07-07 15:00
Ah...nevermind. There's a second parameter to importNode for `deep` import. If you set that to true, it's quite a bit slower ;(

**Comment by jdanyow** [comment] 2016-07-07 15:23
@EisenbergEffect sorry about that- I forgot to update the issue... nothing on the stackoverflow front either.

I think this means the recommendation will be to use `src.bind="'http://video.webmfiles.org/big-buck-bunny_trailer.webm'"` instead of `src="http://video.webmfiles.org/big-buck-bunny_trailer.webm"` right?

**Comment by EisenbergEffect** [comment] 2016-07-07 15:26
I think that's probably the best recommendation for now. In the future, maybe we can find a better solution. I'll close this since we have a resolution. If someone else has the issue or complains that this technique doesn't work, we can revisit it.

**Closed by EisenbergEffect** 2016-07-07 15:26 UTC
Labels: bug
