### ISSUE TITLE
getting Uncaught (in promise) TypeError: capture._resolve is not a function(…)

### ISSUE THREAD

**Issue by amitfou** [aurelia/templating#383] opened 2016-06-14 06:17 UTC
aurelia-templating.js:181 Uncaught (in promise) TypeError: capture._resolve is not a function(…)_tryCompleteTransaction @ aurelia-templating.js:181token.waitForCompositionComplete @ aurelia-templating.js:192(anonymous function) @ aurelia-templating.js:4310

**Comment by Souldrinker** [comment] 2016-06-14 07:45
Yup, got the same issue here in v3.0.0. Setting aurelia-templating hard in the package.json back to 1.2.7, got my app working again, but I hope this will get resolved quickly before I forget I added that line there ;-)

**Comment by ashanvabs** [comment] 2016-06-14 11:06
+1

**Comment by Thanood** [comment] 2016-06-14 11:24
I can confirm that.
The problem seems to be here:

```javascript
        if (this._ownershipToken !== null) {
          var capture = this._ownershipToken;
          this._ownershipToken = null;
          capture._resolve();
        }
```

After `this._ownershipToken = null;` capture is also `null`.

**Comment by RWOverdijk** [comment] 2016-06-14 12:50
👍

**Comment by EisenbergEffect** [comment] 2016-06-14 14:41
Try the latest release, just pushed out. The bug above was introduced in an attempt to get bluebird to stop complaining. That PR we took had a timing issues in it apparently. I think that is solved now. Give it a try and let me know if everything is working again.

**Comment by EisenbergEffect** [comment] 2016-06-14 14:51
Should be fixed now. Apologies for the regression.

**Closed by EisenbergEffect** 2016-06-14 14:51 UTC

**Comment by jrigsby** [comment] 2016-06-14 14:55
I dont know if its related but I was watching for this fix given I was having the same issue.  When I just did a jspm update to get it I am now getting the following

aurelia-pal.js?bust=1465915832974:38 Uncaught (in promise) Error: Error invoking RouterView. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: that is not defined
Inner Error Stack:
ReferenceError: that is not defined
    at new CompositionTransactionNotifier (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:150:7)
    at CompositionTransaction.enlist (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:203:14)
    at new RouterView (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating-router@1.0.0-beta.1.2.1/router-view.js?bust=1465915832974:113:70)
    at Object.invokeWithDynamicDependencies (http://localhost:43436/dist/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.2.0.1/aurelia-dependency-injection.js?bust=1465915832974:314:20)
    at InvocationHandler.invoke (http://localhost:43436/dist/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.2.0.1/aurelia-dependency-injection.js?bust=1465915832974:296:168)
    at Container.invoke (http://localhost:43436/dist/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.2.0.1/aurelia-dependency-injection.js?bust=1465915832974:560:25)
    at ProviderResolver.get (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:1973:74)
    at Container.get (http://localhost:43436/dist/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.2.0.1/aurelia-dependency-injection.js?bust=1465915832974:497:23)
    at Container.elementContainerGet [as get] (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:2028:17)
    at HtmlBehaviorResource.create (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:3924:58)
End Inner Error Stack
------------------------------------------------

    at new CompositionTransactionNotifier (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:150:7)
    at CompositionTransaction.enlist (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:203:14)
    at new RouterView (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating-router@1.0.0-beta.1.2.1/router-view.js?bust=1465915832974:113:70)
    at Object.invokeWithDynamicDependencies (http://localhost:43436/dist/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.2.0.1/aurelia-dependency-injection.js?bust=1465915832974:314:20)
    at InvocationHandler.invoke (http://localhost:43436/dist/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.2.0.1/aurelia-dependency-injection.js?bust=1465915832974:296:168)
    at Container.invoke (http://localhost:43436/dist/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.2.0.1/aurelia-dependency-injection.js?bust=1465915832974:560:25)
    at ProviderResolver.get (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:1973:74)
    at Container.get (http://localhost:43436/dist/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.2.0.1/aurelia-dependency-injection.js?bust=1465915832974:497:23)
    at Container.elementContainerGet [as get] (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:2028:17)
    at HtmlBehaviorResource.create (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:3924:58)
End Inner Error Stack
------------------------------------------------

    at new AggregateError (http://localhost:43436/dist/jspm_packages/npm/aurelia-pal@1.0.0-beta.1.3.0/aurelia-pal.js?bust=1465915832974:38:13)
    at Container.invoke (http://localhost:43436/dist/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.2.0.1/aurelia-dependency-injection.js?bust=1465915832974:562:15)
    at ProviderResolver.get (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:1973:74)
    at Container.get (http://localhost:43436/dist/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.2.0.1/aurelia-dependency-injection.js?bust=1465915832974:497:23)
    at Container.elementContainerGet [as get] (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:2028:17)
    at HtmlBehaviorResource.create (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:3924:58)
    at applyInstructions (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:2122:33)
    at ViewFactory.create (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:2338:9)
    at HtmlBehaviorResource.create (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:3936:41)
    at eval (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.1/aurelia-templating.js?bust=1465915832974:4358:18)

**Comment by EisenbergEffect** [comment] 2016-06-14 14:56
Hold on. Fix is coming....

**Comment by EisenbergEffect** [comment] 2016-06-14 14:59
Ok, fixed and released. Try updating again please :)

**Comment by jrigsby** [comment] 2016-06-14 15:03
Resolved for me.  Thanks
