### ISSUE TITLE
problems using @inlineView

### ISSUE THREAD

**Issue by Thanood** [aurelia/templating#252] opened 2016-01-21 12:11 UTC
Are there any known problems with using ```@inlineView```?

The following class is not rendered. In fact, the application which uses that class stops at:
```DEBUG [aurelia] Configured plugin aurelia-materialize-bridge.``` (which is the plugin the component is defined in).
Unfortunately, it does so without any error message.

When I copy the template into a separate ```.html```file, all works.

Implementation:
```javascript
import { bindable, bindingMode, customElement, inject, inlineView } from 'aurelia-framework';

@customElement('md-card')
@inject(Element)
@inlineView(`
  <template>
  <div class="card">
    <div class="card-content">
      <span class="card-title">${title}</span>
      <card>
      <content></content>
      </card>
    </div>
  </div>
  </template>
`)
export class MdCard {
  @bindable({
    defaultBindingMode: bindingMode.oneTime
  }) title;

  constructor(element) {  }
}

```

**Comment by EisenbergEffect** [comment] 2016-01-21 14:11
I can see that your inline view does not require the `card` element. Is that global?

**Comment by Thanood** [comment] 2016-01-21 14:19
Right, sorry.. Somehow I've got the impression that it was a valid Html5 element.
Changed it to ```<div>``` for clarity (see below). Unfortunately that doesn't change anything.

```javascript
import { bindable, bindingMode, customElement, inject, inlineView } from 'aurelia-framework';

@customElement('md-card')
@inject(Element)
@inlineView(`
  <template>
  <div class="card">
    <div class="card-content">
      <span class="card-title">${title}</span>
      <div>
      <content></content>
      </div>
    </div>
  </div>
  </template>
`)
export class MdCard {
  @bindable({
    defaultBindingMode: bindingMode.oneTime
  }) title;

  constructor(element) {

  }
}
```

**Comment by EisenbergEffect** [comment] 2016-01-21 14:22
Ok, I'll assign this to myself and take a look. I'm not sure what the issue would be just looking at it.

**Comment by Thanood** [comment] 2016-01-21 14:24
Thank you! :smile:

**Comment by EisenbergEffect** [comment] 2016-01-25 20:40
Ok, it's not a bug in Aurelia. Sorry I didn't catch this from first looking at your code, you need to escape the interpolation because that is actually JS syntax for interpolation. You need this:

```
<span class="card-title">\${title}</span>
```

I was debugging in Chrome and received an error that "title was not defined" which clued me in to the problem. What browser were you using? did you see a similar error?

**Closed by EisenbergEffect** 2016-01-25 20:40 UTC
Labels: bug

**Comment by Thanood** [comment] 2016-01-25 21:05
Interesting. I'm using chrome, too and I haven't seen any errors. But maybe they were "eaten" by an unresolved promise rejection. But the debugger stops at this template when it's set to stop at uncaught exceptions.

Babel output also looked reasonable to me:
```javascript
'<span class="card-title">' + title + '</span>'
```

Anyway, thanks for the hint.

**Comment by EisenbergEffect** [comment] 2016-01-25 21:08
No problem. If you discover where the error is being swallowed in your project, please let us know so we can improve that inside Aurelia.

**Comment by smithaitufe** [comment] 2016-10-14 19:05
Please is there a way inlineView can be improved upon to allow interpolation without escaping?

**Comment by JNotelddim** [comment] 2018-12-20 00:04
Where could I find a list of all the characters which need escaping?

I'm trying to move the view markup for some small custom-elements into the view-model files, though it kind of ruins the appeal of inline html when it's all escaped like that. My current element is looking like:
(I'm aware that the `text-content.two-way=` isn't functional with the current value, I'm just leaving it to elaborate on my issue of escaping)
```
import { inlineView, customElement, bindable, bindingMode } from "aurelia-framework";

const markup = 
    `<template>
        <div text-content\.two-way="\(textString \!\= null \? textString \: placeholder\)"
                contenteditable\.bind="isEditing"
                dblclick\.delegate="startEditing()"
                blur\.trigger="finishEditing()">
        </div>
    </template>`

@inlineView(markup)
@customElement('text-div')
export class TextDivCustomElement {

    @bindable({defaultBindingMode: bindingMode.twoWay}) textString: string;
    ...
}
```

/ Could someone elaborate a bit on why they need escaping? I'm not fully understanding.

**Comment by huochunpeng** [comment] 2018-12-20 00:33
In es6
`` `string-interpolation ${jsValue}` ``


We use `${jsValue}` to inline a JavaScript value. But in Aurelia view template, we want literally string `"${to_be_evaluated_by_aurelia_NOT_JavaScript}"`, so we use
```
`real \${string}`
```
To bypass es6 string interpolation, the `\$` will result into just one `"$"` char in string content.

So you only need to escape `\$` and `` \` ``, there is no need to escape `.` or `!` or `?`...

**Comment by huochunpeng** [comment] 2018-12-20 00:44
One way to avoid escaping `$` sign is to avoid back-tick syntax, use old single quote (don't use double quote, otherwise you need to escape lots of double quote in html) with back-slash to support multiple lines.

The trade-off is now you need to escape single quote if there is any.

```JavaScript
const str = '<template>\
  ${value}\
</template>\
';
```
Make sure there is no extra spaces at right side of `\`, otherwise syntax error.

Note the back-slashes are NOT part of the string, they are to tell JavaScript engine to join two lines. It also means if you want new lines, you have to do it literally.


```js
const str = '<template>\n\
  ${value}\n\
</template>\n\
';
```

**Comment by JNotelddim** [comment] 2018-12-20 00:50
@huochunpeng  ok thanks - that's really helpful. 
Yeah I was finding that when I was changing 
```const markup = 
    `<template>
        <div text-content\.two-way="textString"
                contenteditable\.bind="isEditing"
                dblclick\.delegate="startEditing()"
                blur\.trigger="finishEditing()">
        </div>
    </template>`
```
to
```const markup = 
    `<template>
        <div text-content.two-way="textString"
                contenteditable.bind="isEditing"
                dblclick.delegate="startEditing()"
                blur.trigger="finishEditing()">
        </div>
    </template>`
```
that my component could no longer load 😅 but... that's not happening anymore? so I'll trust that whatever i was doing wrong, I managed to unconsciously fix 😂 
Thanks for your help!

**Comment by ChristianKienle** [comment] 2019-02-20 09:21
Another approach would be to use `{{value}}` instead of `${value}`. In Vue this is even configurable:

https://vuejs.org/v2/api/#delimiters

**Comment by EisenbergEffect** [comment] 2019-02-21 02:26
@fkleuver Do we have this as a configuration option in vNext?

**Comment by baerrach** [comment] 2019-07-10 05:24
This problem will bite you when you are trying to do https://aurelia.io/docs/plugins/store#using-the-dispatchify-higher-order-function

The pages `app.html` contains the repeat statement, trying to push this into the example `framework-list` by cut-and-paste gives you an error, but putting into its own view file didn't. That's what brought me here.
