### ISSUE TITLE
Empty object injected as the Element for custom attributes

### ISSUE THREAD

**Issue by jack4it** [aurelia/templating#609] opened 2018-03-27 08:27 UTC
**I'm submitting a bug report**

* **Library Version:**
    "aurelia-animator-css": "^1.0.4",
    "aurelia-binding": "^1.7.1",
    "aurelia-bootstrapper": "^2.2.0",
    "aurelia-cookie": "^1.0.10",
    "aurelia-event-aggregator": "^1.0.1",
    "aurelia-framework": "^1.1.5",
    "aurelia-history": "^1.1.0",
    "aurelia-history-browser": "^1.1.1",
    "aurelia-http-client": "^1.2.1",
    "aurelia-router": "1.5.0",
    "aurelia-validation": "^1.1.3",

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
9.8.0

* **NPM Version:**
5.8.0

* **Yarn Version:**
1.5.1

* **JSPM OR Webpack AND Version**
webpack 4

* **Browser:**
Chrome 65

* **Language:**
TypeScript 2.7.2

**Current behavior:**
All custom attributes suddenly stop working after upgrading to all latest versions of the Aurelia packages along with the webpack 4 upgrade. Debugging shows that the injected Element for the attributes instances is an empty object.

**Expected/desired behavior:**
The injected Element should be the valid DOM element like it has always been. Now all my custom attributes are broken

**NOTE: I'm not using the CLI. I'm building with webpack via a node script**

**Comment by StrahilKazlachev** [comment] 2018-03-27 08:30
Just a sanity check, can you delete any `package-lock.json` file and do a clean install?

**Comment by jack4it** [comment] 2018-03-27 08:32
I'm actually using yarn and have tried to delete the yarn.lock file a couple of times and no luck... but, let me try npm install

**Comment by jack4it** [comment] 2018-03-27 08:39
Just tried `npm install` with no lock file in the first place. Exactly the same broken behavior. This happens to multiple different custom attributes in my codes.

**Comment by StrahilKazlachev** [comment] 2018-03-27 08:39
Then can you update the issue description by substituting the **NPM** section with **Yarn**, with the appropriate version.
Also can you specify whether your build is using the CLI?

**Comment by jack4it** [comment] 2018-03-27 08:42
Just updated the issue according to your comment

**Comment by Alexander-Taran** [comment] 2018-03-27 11:14
Usually it is a forgotten @autoinject
can you create a gist of one of custom elements?
https://gist.run/?id=8ae06845f2bdf4d533b072c00da82614

**Comment by jack4it** [comment] 2018-03-27 21:53
@Alexander-Taran Thanks for the reply. No, the `@autoinject` has been there for almost a year and has been working well until this upgrade. I guess another thing I can try is to only upgrade one library at a time to isolate the problem...

**Comment by Alexander-Taran** [comment] 2018-03-27 23:04
@jack4it please a sample of one of your attributes/elements with injection

**Comment by jack4it** [comment] 2018-03-27 23:18
Sure, here is one of them. It basically turns a `<select/>` into a `bootstrap-select`.

```typescript
import { autoinject, bindable } from 'aurelia-framework';
import $ from "jquery";
import "bootstrap-select";

@autoinject
export class BootstrapSelectCustomAttribute {
  $el: JQuery;

  @bindable
  value: string;

  @bindable
  refreshTrigger: any;

  constructor(element: Element) {
    this.$el = $(element);
  }

  valueChanged(newValue: string) {
    setTimeout(() => {
      this.$el.selectpicker("val", newValue);
    });
  }

  refreshTriggerChanged(newValue: string) {
    setTimeout(() => {
      this.$el.selectpicker("refresh");
      this.$el.selectpicker("val", this.value);
      this.value = this.$el.selectpicker("val");
    });
  }

  attached() {
    this.$el.selectpicker();
    this.$el.on("changed.bs.select", () => {
      this.value = this.$el.selectpicker("val");
    });
  }

  detached() {
    this.$el.selectpicker("destroy");
    this.$el.off("changed.bs.select").remove();
  }
}
```

**Comment by fkleuver** [comment] 2018-03-27 23:24
You're talking about almost a year. There used to be a workaround for `Element` not registering correctly as `DOM.Element`, causing this exact issue. That bug is fixed now, and perhaps the workaround is still present in your project, effectively breaking it again.

Do you have any custom_typings definition files in your project with an `Element` declared somewhere?

For completeness sake, could you share your `tsconfig.json`?

**Comment by jack4it** [comment] 2018-03-28 01:52
Here is the `tsconfig.json`. I also double checked the entire code base, no custom Element declaration existed. Also I tried to use `DOM.Element` instead of `Element`, however, it doesn't seem to be a valid expression at all, like below:

![image](https://user-images.githubusercontent.com/3120462/38004176-eb7f0e62-31ef-11e8-83a1-2e17c88064db.png)

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "lib": [ "es2015", "dom" ],
    "module": "es2015",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "outDir": "wwwroot/dist",
    "removeComments": true,
    "rootDir": "src/",
    "sourceMap": true,
    "target": "es5"
  },
  "filesGlob": [
    "./src/**/*.ts",
    "./**/*.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by fkleuver** [comment] 2018-03-28 03:07
`DOM.Element` can only be injected directly like so: `@inject(DOM.Element)`. This will be matched by parameter index and the type definition on the constructor will be ignored.

I don't see any obvious problems here, but trying that `@inject` would rule out whether the problem is DI-related (thereby possible bundler-related) or if there's something else going on..

**Comment by jack4it** [comment] 2018-03-28 09:15
@fkleuver good point, just tried `@inject` and it's working. So likely the issue is that the new `webpack4` upgrade caused the issue. @jods4 have you noticed this issue?

**Comment by StrahilKazlachev** [comment] 2018-03-28 10:18
@jack4it you can use `DOM.Element` as types like this: `typeof DOM.Element` so
```js
constructor(element: typeof DOM.Element) {
}
```
You may need to cast parameter when using it inside the constructor though.

**Comment by Alexander-Taran** [comment] 2018-03-28 10:48
@StrahilKazlachev that is so should go to docs..

**Comment by fkleuver** [comment] 2018-03-28 11:47
@jack4it What's interesting is that this used to be a problem in the past, but it was fixed at some point. I'm honestly a little surprised that that worked for you (though even more so that it broke in the first place).

I have been autoinjecting elements as plain `: Element` via constructors at least for the last few months without issues, all with the latest packages, recently upgraded to webpack 4, etc.

The bottom line is: what you're doing really *should* work. `DOM.Element` and `Element` are meant to point to the same thing.

Could you F12 to the definition of `Element` and verify that it leads you do `lib.dom.d.ts` which has both an Element interface *and* this in it:

```ts
declare var Element: {
    prototype: Element;
    new(): Element;
};
```

Then doing a "find all references" on that var declaration should point you towards `aurelia-pal.d.ts` which has this in it:

```ts
export declare interface Dom {
  
  /**
    * The global DOM Element type.
    */
  Element: typeof Element;
```
This var declaration is crucial for the DI container since as you probably know, interfaces aren't emitted. We've confirmed that `DOM.Element` works, so for one reason or another the compiler stops looking after it cleans the `Element` interface and doesn't end up emitting any type metadata for it.

**Comment by jack4it** [comment] 2018-03-28 17:03
@fkleuver Thanks for the detailed information. I did F12, it leads to `lib.dom.d.ts` and shows the two definitions. But the "find all references" leads to nowhere and said `No results`. Something wrong with my 'aurelia-pal' package reference?

**Comment by fkleuver** [comment] 2018-03-29 02:45
Well, there's certainly something wrong in that direction but it's probably coming from how the types are resolved. If you look at `node_modules\aurelia-pal\dist\aurelia-pal.d.ts`, do you see the declaration I mentioned earlier? If you hover over you should see it pointing to that `var` declaration from the `lib.dom.d.ts`:

![image](https://user-images.githubusercontent.com/9655331/38067073-14011a4e-330b-11e8-948e-a01bc737e998.png)

And just to rule a few things out, could you try changing `"module": "es2015"` to `"module": "amd"` and remove `"rootPath"` entirely?

Might be asking the obvious here, but you've already deleted the `package-lock.json` and `yarn.lock` as well as clear the `node_modules` folder and then did a fully clean install? Those lock files have a tendency to keep inconsistent versions sticking around after upgrading.

Lastly, could you show the `ts-loader` part(s) of your webpack config?

**Comment by jack4it** [comment] 2018-03-29 07:34
Yes, lock files and `node_modules` removed, clean install after that. Also when I open `aurelia-pal.d.ts` i can see the correct Element references. Following is the ts-loader.

```
        {
          test: /\.ts$/i,
          loader: "ts-loader",
          options: {
            transpileOnly: true // IMPORTANT! use transpileOnly mode to speed-up compilation
          }
        },
```

**Comment by jack4it** [comment] 2018-03-29 07:45
whoa, found the issue. Great reminder on `ts-loader`. Notice that I have configured `transpileOnly` and `ForkTsCheckerWebpackPlugin` based on https://blog.johnnyreilly.com/2018/02/ts-loader-400-fork-ts-checker-webpack.html. After changing the config back, the `@autoinject` with `Element` immediately gets back to work. I'm not able to tell what exactly happens inside the ts-loader/TS processing, but that was apparently the reason why Aurelia failed to inject `Element`. I think I will stay with `@inject` for now. Thanks to everyone for the help!!!

**Comment by Alexander-Taran** [comment] 2018-03-29 07:52
@jack4it can you close this one then?

**Closed** 2018-03-29 07:52 UTC
