### ISSUE TITLE
`repeat.for` ordering issue with custom element container

### ISSUE THREAD

**Issue by alexanderteinum** [aurelia/templating#246] opened 2016-01-13 09:59 UTC
I would expect the following to render a list with values 1, 2, 3, 4. Instead, it renders 1, 4, 2, 3. See [complete example](https://github.com/alexanderteinum/beginner-kits/blob/master/kit-es2016/src/app.html).

#### `app.html`

```html
…
<c-ul>
  <li>1</li>
  <li repeat.for="item of [2, 3]">${item}</li>
  <li>4</li>
</c-ul>
…

```
#### `c-ul.html`

```html
<template>
  <ul><content></content></ul>
</template>
```

#### `c-ul.js`

```js
import {customElement, containerless} from 'aurelia-framework';

@customElement('c-ul')
@containerless()
export class CustomUl {
}
```

**Comment by EisenbergEffect** [comment] 2016-01-13 14:52
Thanks for the sample code. I'll take a look.

**Comment by EisenbergEffect** [comment] 2016-01-25 23:28
I've reproduced this bug. It's an issue in our shadow dom fallback implementation. We are planning to update that implementation to the shadow dom v1 spec in the near future. That will mean some massive internal implementation changes. As part of that update, we'll address this issue.

**Comment by EisenbergEffect** [comment] 2016-05-17 15:39
Closing this since it's now fixed in the new shadow dom implementation, residing in a branch and preparing for release soon.

**Closed by EisenbergEffect** 2016-05-17 15:39 UTC
Labels: bug
