### ISSUE TITLE
repeat.for renders empty items

### ISSUE THREAD

**Issue by valichek** [aurelia/templating#197] opened 2015-10-26 11:28 UTC
After last update (from __0.15.3__ to __0.16.0__) I got strange rendering with repeat.for.
It renders __empty__ items when I switch its source list from not empty array (`arr1`) to `null` and back to not empty array (`arr2`), so after switching to `arr2` there are empty items (same number as in `arr1`) + items from `arr2`. And this behavior is accumulative, so if I toggle from arr1=>null=>arr2=>null=>arr1 it will render arr1.length + arr2.length empty elements + elements from arr1

**Comment by devteamexpress** [comment] 2015-10-28 13:39
I'm experiencing this issue as well.

**Comment by paulbrickellmaven** [comment] 2015-10-28 14:55
I'm not sure this problem is so new. I was seeing this behaviour months back. I never did resolve it and ended up using if.bind on a flag to remove a containing element when switching.

**Comment by pbrickell** [comment] 2015-10-28 14:57
I'm not sure this problem is so new. I was seeing this behaviour months back. I never did resolve it and ended up using if.bind on a flag to remove a containing element when switching.

**Comment by devteamexpress** [comment] 2015-10-28 15:20
It seems to happen to me when i use a child router and switch between routes.

**Comment by valichek** [comment] 2015-10-28 15:23
@pbrickell, the good way to avoid it is not to use `null` but just empty array `[]`

**Comment by martingust** [comment] 2015-10-28 21:04
@valichek Was not able to reproduce this issue. Can you please provide steps to replicate or example project?

**Comment by EisenbergEffect** [comment] 2015-11-09 07:46
Can anyone tell us how to reproduce this issue? If not, we can't fix it. A simple set of steps or a basic reproduction is what we need.

**Comment by devteamexpress** [comment] 2015-11-09 11:03
Sorry for the delay , the issue seems to be more elaborate and i stripped down the project i was using so you have an example to look at

https://github.com/devteamexpress/test-aurelia


If you have a child router and you switch between routes the binding just stops working entirely and i am left with empty fields. I have two screens on my child router (General and Intergrations) start on general go to Intergrations and click the back button you'll see it doesn't bind , furthermore the child router doesn't bind it's routes when you click integrations, sometimes it does bind but with empty elements on the child router for the foreach.

**Comment by devteamexpress** [comment] 2015-11-09 11:04
One thing i would like to add that if i change the binding from a value bind on an input field to a select field then the page fails entirely with cannot find disconnect of null.

**Comment by EisenbergEffect** [comment] 2015-11-09 20:37
@devteamexpress That sample has too much going on and doesn't appear to be related to this issue.

Does anyone have a simple sample that demonstrates the repeater problem in isolation?

**Comment by devteamexpress** [comment] 2015-11-09 21:27
This may not be only about the repeat.for, but this is the issue that is holding back our company from releasing a live app. Anytime we use a child router and switch between routes the binding doesn't work. 

I tried to dumb down the app were using to it's simplest form, please let me know what other information i can give you so we can tackle this issue.

**Comment by EisenbergEffect** [comment] 2015-11-09 21:33
@devteamexpress  If you have a routing issue, please report that on the router repo. That will notify the team members that work on routing.

**Comment by devteamexpress** [comment] 2015-11-09 21:36
@EisenbergEffect done 

https://github.com/aurelia/router/issues/245

**Comment by EisenbergEffect** [comment] 2015-11-10 20:49
I never had anyone provide a repro for this particular issue. Can someone try their code against the latest release and let me know if it's fixed. If not, can a repro be provided?

**Comment by jdanyow** [comment] 2015-11-17 13:20
https://github.com/aurelia/templating-resources/issues/144 was a duplicate of this issue.  It's now fixed

**Closed by jdanyow** 2015-11-17 13:20 UTC
