### ISSUE TITLE
bindable using view model not working as before beta-1.1.0

### ISSUE THREAD

**Issue by doktordirk** [aurelia/templating#258] opened 2016-02-03 18:28 UTC
previously (beta-1.0.3)
``` html
<template bindable="xy">
```
would bind xy whether there was a view model used or not.
with beta-1.1.0 that only works if no view model is used.

test with skeleton app:
``` javascript
// add a nav-bar.js
export class NavBar {}
```
``` html
<!--change app.html to -->
<template>
  <require from="nav-bar"></require>
...
```

explicitly binding in the view model as follows still works. 
``` javascript
//  nav-bar.js
import {customElement, bindable} from 'aurelia-framework';

@customElement('nav-bar')
export class NavBar {
  @bindable router;
}
```

that change in behaviour is intended?

**Comment by EisenbergEffect** [comment] 2016-02-03 18:31
I'm not quote following. Forgive me. Would you mind explaining a bit more? Thanks.

**Comment by doktordirk** [comment] 2016-02-03 18:36
previously 
<template bindable="router">

would do the same as
`` `javascript
//  nav-bar.js
import {customElement, bindable} from 'aurelia-framework';

@customElement('nav-bar')
export class NavBar {
  @bindable router;
}
```

as of beta-1.1.0 bindable="router" does not bind the router anymore. only binding via  @bindable router; works now.
thats' only if a nav-bar.js is used. with require from html
``` html
<!--change app.html to -->
<template>
  <require from="nav-bar.html"></require>
...
```
the
<template bindable="router">
still binds

**Comment by EisenbergEffect** [comment] 2016-02-03 18:40
Wait, you are saying that adding "bindable" properties in the template doesn't work at all? I just tested that in the skeleton the other day though...

**Comment by doktordirk** [comment] 2016-02-03 18:41
only if a view model is used. without view model it works

**Comment by doktordirk** [comment] 2016-02-03 18:50
made a branch to make it clearer
https://github.com/doktordirk/skeleton-navigation/commit/a42846ce77a11aa152a846c2a6b96bbd485840e0

**Comment by EisenbergEffect** [comment] 2016-02-03 19:21
Ok, if that worked before...it was a regression in the previous version. Bindables in a template require the absence of an explicit view model. My guess is that it didn't work but only appeared to because the parent binding context had properties of the same name that got inherited through. There was a regression in the beta that allows encapsulation to break. That has been fixed in this release.

**Closed by EisenbergEffect** 2016-02-03 19:21 UTC

**Comment by doktordirk** [comment] 2016-02-03 19:23
alright
