### ISSUE TITLE
Bug: Aurelia does not respect Promise exceptions returned through ViewModel.activate( )

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/templating#356] opened 2016-05-23 01:56 UTC
My particular use-case consists of returning a Promise from activate( ) in order to permit my ViewModel to load resources (layout definitions) asynchronously that will be subsequently used to render the content of the View (via getViewStrategy). In other words, I am forcing Aurelia to wait until my layout definitions are loaded.

Everything works perfectly when there are no exceptions.

If the promise chain (as identified by the promise returned by activate) throws an exception, then Aurelia exhibits some problems:

- No failure is reported to the console, which seems contrary to other areas (such as the router) which do report exceptions to the console.
- Aurelia seems to become "stuck" in the sense that other views can no longer be loaded. The browser address bar changes to the new view but the content does not appear.
- ~~I am fairly positive that on at least some occasions, Aurelia will continue the process of instantiating a view after the activate( ) promise exception has occurred, but in later variants of my application I have not been able to reproduce.~~

**Comment by EisenbergEffect** [comment] 2016-05-23 03:05
What would you expect or like to happen in this case?

**Comment by jsobell** [comment] 2016-05-24 03:36
I have also experienced this issue in my app, but I just tried creating a GistRun of it and I can't reproduce it in isolation :)
The lack of throw error is one thing (yes, some feedback would be nice) but the main issue is the 'frozen' nature of the interface, where no links have any effect once an exception was thrown.
Here's a GistRun that **does not** show the issue (https://gist.run/?id=bfed0ca47d109a09d5b9d19bc46bcd33) , but @kevmeister68 , if you can modify this to replicate the issue you're seeing, that would make it easier to demonstrate and suggest solutions.

**Comment by EisenbergEffect** [comment] 2016-07-07 19:33
Ok, I'm closing the issue since I can't reproduce the "stuck" behavior. I have been able to reproduce the no error on the console behavior though. This results from throwing a string, instead of an Error object. Though it's possible to throw anything (I think) it's not recommended to throw anything other than an Error object. If you stick to that best practice, Aurelia should be able to report error during activation correctly to the console.

**Closed by EisenbergEffect** 2016-07-07 19:33 UTC
