### ISSUE TITLE
Strange Error randomly

### ISSUE THREAD

**Issue by devteamexpress** [aurelia/templating#328] opened 2016-04-27 07:47 UTC
Some of our users will randomly get this error in the console. 

    "TypeError: Unable to get property 'length' of undefined or null reference\n   at e.prototype.loadTemplateResources (https://d1mui8ymn9ttgd.cloudfront.net/framework.js:10:27988)\n   at Anonymous function (https://d1mui8ymn9ttgd.cloudfront.net/framework.js:10:27585)\n   at s (https://d1mui8ymn9ttgd.cloudfront.net/framework.js:3:27102)\n   at Anonymous function (https://d1mui8ymn9ttgd.cloudfront.net/framework.js:3:27248)\n   at c (https://d1mui8ymn9ttgd.cloudfront.net/framework.js:3:23371)"

Does anyone have an idea as to what might be the cause.

**Comment by EisenbergEffect** [comment] 2016-04-27 12:20
We've never seen this before. We would need a reproduction to see if it's in our code and how to fix it.

**Comment by EisenbergEffect** [comment] 2016-07-06 02:41
Closing since we can't reproduce and have no additional info from the OP that could help us.

**Closed by EisenbergEffect** 2016-07-06 02:41 UTC
