### ISSUE TITLE
Rendered `repeat.for` template does not match array contents in customElement

### ISSUE THREAD

**Issue by cb-fred** [aurelia/templating#524] opened 2017-02-14 14:25 UTC
**I'm submitting a bug report**

* **Library Version:**
```
├─┬ aurelia-framework@1.0.8
│ ├── aurelia-binding@1.1.1
│ ├── aurelia-loader@1.0.0
│ ├── aurelia-task-queue@1.1.0
│ └── aurelia-templating@1.2.0
```

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.4
* **Node Version:**
v7.5.0

* **NPM Version:**
4.1.2

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.27

* **Browser:**
56.0.2924.87 (Official Build) (64-bit)

* **Language:**
ESNext

**Current behavior:**

The rendered template of a for loop doesn't match the iterated array contents, after the array has been modified a few times. The screenshot shows the popup with search results displaying extra values. The real array only contains ['Foobar','Barfoo'], as correctly reported by the printed length, and as verified via console inspection. 

<img width="851" alt="bug" src="https://cloud.githubusercontent.com/assets/19568566/22932719/3c5b08a2-f2c9-11e6-80de-e0fee81a372c.png">

``` element.js

import {inject, customElement, containerless, bindable, bindingMode} from 'aurelia-framework';
import * as utils from '../utils';
import {ObserverLocator} from 'aurelia-binding';

@customElement('autosearch')
@containerless()
@inject(ObserverLocator)
export class Autosearch {

    /* The parent search viewmodel */
    @bindable view;

    /* 
     * The search filter model, watched by the parent search view,
     * modified by this view.
     * {
     *  options: ['foo','bar','xyz'], <- available values
     *  selected: null                <- user selected value
     * }
     */
    @bindable({ defaultBindingMode: bindingMode.twoWay }) model;

    constructor(obsLoc, ...args) {
        this.input = '';
        this.results = [];
        this.obsLoc = obsLoc;
        this.selected = true;           // has the user picked his desired value ?
        this.hasFocus = false;          // raw input focus
        this.hasFocusDelayed = false;   // input focus with a delay before blur.

        obsLoc.getObserver(this,'input')
            .subscribe(() => {
                this.makeResults();
            });

        obsLoc.getObserver(this,'hasFocus')
            .subscribe(() => {
                if (this.hasFocus) {
                    this.hasFocusDelayed = true;
                } else {
                    setTimeout(() => {
                        this.hasFocusDelayed = false;
                    },150);
                }
            });
    }

    attached() {
        this.input = this.model.selected || '';
    }

    makeResults() { // search input in options.
        if (this.input == this.model.selected) {
            return;
        }
        this.selected = false;
        var results = [];
        var pattern = this.input.toLowerCase();
        for (var option of this.model.options) {
            var value = option.toLowerCase();
            if (value.indexOf(pattern) >= 0) {
                results.push(option);
            }
        }
        utils.setArray(this.results, results);
    }

    selectOption(value) {
        this.model.selected = value;
        this.input = value;
        this.selected = true;
        utils.setArray(this.results, []); // Necessary to prevent a crash in aurelia templating. No idea why.
    }
}
```

```utils.js
export function setArray(array, newarray) {
    array.splice(0, array.length);
    for (var i = 0; i < newarray.length; i++) {
        array.push(newarray[i]);
    }
}
```

```element.html
<template bindable='model, view'>
    <div class='cb-search-box' class.bind='input ? "not-empty": ""'>
        <input class='form-control'
        type='text'
        value.bind='input'
        focus.bind='hasFocus'
        t='[placeholder]lbl-search-fidu'
        placeholder='Fiduciary'>
        <span class='cb-search-box-icon'>
            <i if.bind='!view.reloading' class='fa fa-search'></i>
            <i if.bind='view.reloading' class='fa fa-spin fa-gear'></i>
        </span>
        <div if.bind='!selected && hasFocusDelayed' class='cb-search-autocomplete'>
            <template if.bind='results.length'>
                ${results.length}
                <template repeat.for='result of results'>
                    <div class='cb-search-auto-item' 
                         click.delegate='selectOption(result)'>
                        ${result}
                    </div>
                </template>
            </template>
            <template if.bind='!results.length'>
                <div class='cb-search-auto-item' t='lbl-no-results'>lbl-no-results</div>
            </template>
        </div>
    </div>
</template>
```

**Comment by jdanyow** [comment] 2017-02-20 06:16
@cb-fred can you put together a gist that demonstrates this issue? 

https://gist.run/?id=7542e061bc940cde506b

thanks!

**Comment by cb-fred** [comment] 2017-02-23 10:42
Here you go:

https://gist.run/?id=908128384bb416acb84e47a79c9e7a0d

How to reproduce:

 - Type `foo` in the input
 - click on foobar
    - Should show 2 | Foobar | Barfoo
 - Select input contents again
 - Type `foo`
   - Should show 2 | Foobar | Barfoo | Foobar | Barfoo

**Comment by jdanyow** [comment] 2017-02-23 14:34
thanks @cb-fred - that's a complicated repro, it may be a little while before I'm able to dig through that.  If you're able to distill that down to a smaller example that would be helpful.

In the meantime, here's a pure aurelia [autocomplete](https://gist.run/?id=acf8253329939b2e046cd0e3394351fe). Not sure if it's exactly what you need but it maybe it will be a workaround for you.

**Comment by cb-fred** [comment] 2017-02-23 15:06
Here's an updated gist with some removed cruft https://gist.run/?id=a3aeaf423c3805fbcbf1cabfd2c3c91e

Also look at the FIXME in element.js, if you remove that line you'll _sometimes_ get crashes in the aurelia framework, it's probably related. 

I'm not in a hurry for the bugfix, but such a bug makes me a bit paranoid as other part of the app uses similar mechanisms to provide other kinds of searches

Anyway thanks for investigating this issue.

**Comment by cb-fred** [comment] 2017-03-07 16:00
Any news ?

**Comment by fabioluz** [comment] 2017-03-14 15:01
@cb-fred The problem is this line:

`<div if.bind='!picked && hasFocusDelayed'>`

If you change it to `<div if.bind='results.length'>` and remove the next `<template>`, the items will be shown correctly. The `picked` property is unnecessary, you can remove it. See this simplified version of your code https://gist.run/?id=45617c25421eac37be599595d7fda593. I believe this solves your problem by now.

--------

@jdanyow it seems to be a bug in `if.bind` where it runs the `repeat.for` twice. See this gist https://gist.run/?id=17248ad4f259fe5b870a5929b7c6a54a. Uncomment the first div and you'll see the error.

To reproduce the error: 

- Type 'o'
- Click the first Item
- Type 'o' again

I'll try to dig into this. I'll post here if I find something.

**Comment by fabioluz** [comment] 2017-03-16 20:26
@EisenbergEffect @jdanyow I've found the problem!

## **To reproduce the error**

- Open https://gist.run/?id=17248ad4f259fe5b870a5929b7c6a54a
- Uncomment the divs
- Type 'o'
- Click the first item
- Click somewhere else (to lose focus from input text)
- Select the current text and type 'o'

## **Tracing the bug**

When the user changes `input` to 'o', Aurelia:
  - Enqueues SetterObserver for `input` => 'o'
  - Enqueues SetterObserver for `picked` => false
  - Enqueues ModifyArrayObserver for `results` =>
      - Changes[0] => splice(0, array.length);
     -  Changes[1] => push('Foobar') 
     -  Changes[2] => push('Barfoo')
     -  Changes[3] => push('HelloWorld')
 
End of the method. Flushing the queue...

- Calls SetterObserver for `input`
  - irrelevant...
- Calls SetterObserver for `picked`
  - Triggers `if` from `<div if.bind='!picked && hasFocusDelayed'>`
     - Triggers `if` from `<template if.bind='results.length'>`
       - Triggers `repeat` from `<template repeat.for='result of results'>`
       - View at this point: ![2017-03-16 2](https://cloud.githubusercontent.com/assets/5049361/24016099/9d754a64-0a69-11e7-9ea3-d64920e89a7a.png)
- Calls ModifyArrayObserver for `results`
   - Triggers `repeat` from `<template repeat.for='result of results'>` **Instead of being updated, Repeater is being rendered AGAIN**
     - View at this point ![2017-03-16 3](https://cloud.githubusercontent.com/assets/5049361/24016407/bbf4a8c6-0a6a-11e7-8f59-e7553a5e9274.png)
   -  Enqueues SetterObserver for `$index` of `results` => 3 - ChildInterpolationBinding
   -  Enqueues SetterObserver for `$index` of `results` => 4 - ChildInterpolationBinding
   -  Enqueues SetterObserver for `$index` of `results` => 5 - ChildInterpolationBinding
- Calls SetterObserver for `$index` of `results`
- Calls SetterObserver for `$index` of `results`
- Calls SetterObserver for `$index` of `results`
- View at this point ![2017-03-16 4](https://cloud.githubusercontent.com/assets/5049361/24016582/7fd63c96-0a6b-11e7-934b-9924e4f6628c.png)

I'll study templating and templating-resources and try to fix it when I have time. If you have some idea of where to start, or if you don't want fix it now for some reason, please tell me :)

**Comment by bigopon** [comment] 2017-09-26 02:14
I'm having expected behavior, if I didn't missed anything.

Flow:

- Typed `'o'`, see 3 results : `FooBar - 0`, `BarFoo - 1`, `HelloWorld - 2`
- Clicked the first item, lost input focus, text field change to `FooBar - 0`. The instruction is to lose the input focus intentionally but here I lose it as soon as I mouse down on any of the item
- Select the whole text, and change to `'o'`, see 3 results again

Can you update ? @fabioluz

**Comment by fabioluz** [comment] 2017-10-17 18:41
Hmmm it has been months since I tried to track this bug. It's not happening anymore 😆 Perhaps it was fixed with the latest changes.

I would vote for closing this issue.

**Comment by bigopon** [comment] 2017-12-15 12:37
@EisenbergEffect this can be closed.

**Closed** 2017-12-15 17:04 UTC
Labels: bug
