### ISSUE TITLE
Attached / detached lifecycle callbacks not working with layoutViewModel

### ISSUE THREAD

**Issue by ksm2** [aurelia/templating#468] opened 2016-09-28 12:47 UTC
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Arch Linux

* **Node Version:**
6.6.0

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.18

* **Browser:**
Chromium 53

* **Language:**
TypeScript 2.0.1

**Current behavior:**
When used within a layouted route, the attached lifecycle is not called.

**Expected/desired behavior:**

* **What is the expected behavior?**
When I use a custom element or a view model, I expect the attached lifecycle callback to be called at some point. Unfortunately, when using a `layoutViewModel` with my route, this is not happening anymore.

* **What is the motivation / use case for changing the behavior?**
To make senseful use of the layout feature, this has to work. Otherwise important custom elements are not working.

Maybe you could also take a look at my post on SO about layouts, http://stackoverflow.com/questions/38763698/how-to-use-layouts-in-aurelia

Thanks in advance
Konstantin

**Comment by EisenbergEffect** [comment] 2016-09-28 15:14
Duplicate of https://github.com/aurelia/templating-router/issues/34

**Closed by EisenbergEffect** 2016-09-28 15:14 UTC
