### ISSUE TITLE
Templates swapped with Polymer

### ISSUE THREAD

**Issue by roguePanda** [aurelia/templating#90] opened 2015-06-06 14:08 UTC
When using certain Polymer elements in Aurelia templates, insertion points such as string interpolation, `repeat` attributes, and `router-view` outlets change places. In my particular instance, a `paper-item` element generated from router navigation routes ends up where the `router-view` element is and the content of the routed view ends up in the `paper-menu` containing the `paper-item`.

So far, the only Polymer elements I've noticed this with are [`paper-scroll-header-panel`](https://github.com/PolymerElements/paper-scroll-header-panel) and [`paper-drawer-panel`](https://github.com/PolymerElements/paper-drawer-panel). I checked with [`paper-header-panel`](https://github.com/PolymerElements/paper-header-panel), which also selects child content, and didn't run into the issue.

![screen shot 2015-06-06 at 10 00 37 am 6-6-15](https://cloud.githubusercontent.com/assets/1683332/8019885/ec3a7412-0c32-11e5-97c3-bd866f731369.png)

The `<div id="page-host">` containing the highlighted `<paper-item>` contains the `router-view`, and the original source is
```html
 <div id="page-host">
    <router-view></router-view>
</div>
```

The `paper-item` is generated by 

```html
<paper-item repeat.for="route of router.navigation">
    <a href.bind="route.href">${route.title}</a>
</paper-item>
```

I've tried this in both Chrome and Firefox, with Polymer 1.0 and aurelia-templating 0.11.2.

My sample application is [here](https://github.com/roguePanda/polymer-aurelia-web-app).

**Comment by EisenbergEffect** [comment] 2015-06-06 16:04
I'll take a look at it.

**Comment by joshua1** [comment] 2015-07-02 19:40
Hi @EisenbergEffect has this issue been sorted, i am working with both libraries in an application we just started.Thanks

**Comment by EisenbergEffect** [comment] 2015-07-02 19:40
Excellent. What was the issue? We recently made some changes to how our anchors worked. Did that solve it or was there something else going on?

**Comment by EisenbergEffect** [comment] 2015-07-02 19:41
Oops. Sorry I misunderstood you and thought you were saying that it had been solved. I haven't looked into it yet. Is it broken with the absolute latest releases?

**Comment by shabalin** [comment] 2015-07-16 20:36
I've got same issue, here is template code:
```html
<template>

  <paper-drawer-panel force-narrow>
    <paper-header-panel drawer>
      <paper-toolbar></paper-toolbar>
      <div>
        <paper-menu>
          <paper-item repeat.for="route of router.navigation">
            <a href.bind="route.href">${route.title}</a>
          </paper-item>
        </paper-menu>
      </div>
    </paper-header-panel>
    <paper-scroll-header-panel condenses main id="mainScrollPanel">
      <paper-toolbar class="paper-header" id="mainToolbar">
        <paper-icon-button icon="menu" tabindex="1" paper-drawer-toggle></paper-icon-button>
        <span class="title">${router.title}</span>
      </paper-toolbar>
      <div>
        <div class="page-host">
          <router-view></router-view>
        </div>
      </div>
    </paper-scroll-header-panel>
  </paper-drawer-panel>

</template>
```
If i remove <paper-item repeat.for="route of router.navigation"> content in div.page-host is appeared.

I can share my repo if you need

**Comment by mib4fun** [comment] 2015-07-18 11:38
Got the same issue here

**Comment by EisenbergEffect** [comment] 2015-07-26 02:45
In order to investigate this, I will need a full working sample with instructions. The above link did not build for me, so I wasn't able to investigate further.

**Comment by EisenbergEffect** [comment] 2015-07-26 03:06
I got it working. I'm seeing the odd behavior. I have some theories and will look into it.

**Comment by roguePanda** [comment] 2015-07-26 03:38
I'll also update the sample with the latest versions of everything in case that changes anything

**Comment by EisenbergEffect** [comment] 2015-07-26 19:58
@roguePanda Your sample is very hard to work with because you've got a non-standard build and you've pre-built everything into a bundle, which makes it hard to work with. I have an idea of how to fix this, but instead of it taking me 15 minutes to test, it's going to take me much, much longer. As a result, I can't guarantee it will get fixed in this iteration. If someone wants to send me a minimal reproduction based on top of the skeleton with no custom building and bundling, then I can probably deal with this pretty quickly.

**Comment by EisenbergEffect** [comment] 2015-07-26 20:36
Ok, good news. I've figured out how to fix it.

**Comment by roguePanda** [comment] 2015-07-26 20:37
I've been working on a sample based on skeleton-navigation. Do you still need it?

**Comment by roguePanda** [comment] 2015-07-26 20:48
Polymer's [unregistered element bookmarklet](https://www.polymer-project.org/0.5/docs/polymer/debugging.html#unregistered-element-bookmarklet) flags the `nav-bar` custom element as unregistered also, but that could be a separate issue since taking it out doesn't seem to change anything.

**Comment by EisenbergEffect** [comment] 2015-07-26 20:50
Here's a brief explanation:

The Aurelia compiler inspects DOM nodes and extracts data about bindings and behaviors..and generally does as much work ahead of time as it can so that view creation is fast. The extracted "instructions" have previously been tied to DOM structure so that a query selector could discover all au-target elements and then we could simultaneously loop over those and the instructions, applying them as we go.

In the case of these special Polymer elements, the DOM gets manipulated by them during the clone of the template. So, at the earliest point that Aurelia can perform a query selector for targets, those Polymer elements have already re-arranged the DOM. The side-effect is that the ordering of extracted instructions no longer matches the ordering of elements returned from the query.

The only way I know to fix this is to tag every au-target with a unique id and then store the extracted instruction by that id, thus making the view instantiation process independent of the DOM structure. This can only happen with Web Components, so this should fix any scenario where a 3rd party web component alters the DOM during the create (clone) phase.

**Comment by EisenbergEffect** [comment] 2015-07-26 20:51
@roguePanda Aurelia doesn't register its custom elements as web components so that bookmarklet would definitely report them. It has no affect on runtime behavior though. We choose not to do that because our implementation is lighter weight, faster and more deeply integrated with the binding system than a standard web component would be. But bottom line: there's no need to worry about what that bookmarklet reports with regard to Aurelia.

**Comment by EisenbergEffect** [comment] 2015-07-26 20:52
To clarify, I no longer need an additional sample. I was able to confirm that my approach to changes to the compiler and view factory fix the behavior in the provided sample.

**Closed** 2015-07-27 00:47 UTC
Labels: bug

**Comment by EisenbergEffect** [comment] 2015-07-27 00:49
I've pushed a fix for the issue. It should go out in the next update within a few days. Also, if you've been following the official blog, you may have noticed that we like to feature community members. So, if anyone is interested in writing a blog post on using Polymer with Aurelia, just let me know and we would be happy to feature your article on our official blog.
