### ISSUE TITLE
Existence of bind/attached methods change how many times a propChanged method is called

### ISSUE THREAD

**Issue by TagGerr** [aurelia/templating#597] opened 2018-01-10 00:13 UTC
**I'm submitting a bug report**

**Current behavior:**
There appears to be some discrepancy between bind and attached when it comes to propChanged methods.
 * If there is no bind method, the propChanged method is called as expected.
 * If there is a bind method, it will only call the propChanged method if the bind method directly modifies the property.
 * If there is an attached method that directly modifies the property, the propChanged method will be called twice.

https://gist.run/?id=746cc08de1e7968c7cbee8029aac1193
This gist shows 6 different iterations of bind/attached with slightly different outputs. Commenting and uncommenting blocks should show the behavior described above.

**Expected/desired behavior:**
I expected the propChanged method to get called at least once when the value was set—regardless of bind/attached methods existing—or not be called at all unless the value was changed. Just the existence of an empty bind method changing how many times a propChanged method is called confuses me.

**Comment by bigopon** [comment] 2018-01-10 00:22
> It should be noted that when the view-model has implemented the bind callback, the databinding framework will not invoke the changed handlers for the view-model's bindable properties until the "next" time those properties are updated. If you need to perform specific post-processing on your bindable properties, when implementing the bind callback, you should do so manually within the callback itself.

http://aurelia.io/docs/templating/html-behaviors-introduction#html-behavior-lifecycle

-----

As stated from official doc, when you have `bind` life cycle, change handler like `nameChanged` won't be called until you updated it again. Thus having only `attached` without `bind` and updating `name` in `attached` should have it updated twice.

@EisenbergEffect I think the gist in this issue is a good way to document the various behavior of `bind`, which could be handy for many. Maybe we can invite @TagGerr to write some doc for it 😉

**Comment by TagGerr** [comment] 2018-01-10 00:29
Fair enough. I must have read past that exact line a hundred times and never really understood what it was saying, but I get it now. Thank you for the clarification.

Ha, me and documentation... Right!

**Comment by bigopon** [comment] 2018-01-10 03:39
@TagGerr Same thing happened to me. Does it motivate you to help other with this part 😄

**Comment by EisenbergEffect** [comment] 2018-01-10 04:09
Since we are kicking work off on vNext soon. I think this behavior is something we should consider changing in vNext. It seemed like a good idea at the time, but I think it's un-intuitive or unexpected behavior in the end. If we instead always called bind, no matter what, but also always called all the change handlers at the same time after all properties were initially set, perhaps that's a better way? @bigopon I bet you have some thoughts on this.

**Comment by bigopon** [comment] 2018-01-10 09:48
I think initialization and reactive handling of bindings need to be separated. With current behavior of `bind`, we have clear mechanism to say when we have everything ready before reactive bindings kick in. If we were to always call change handlers, probably we would lose initialization and this, I don't feel like a good decision, to to mention the breaking change. For me, the issue stems from word choice, `bound` could have been a better fit, compared to `bind`. Then we need to consider renaming `unbind` to `unbound`. This way, things go well together as all `templating` life-cycles are passive:  `created` -> `bound` -> `attached` -> `detached` -> `unbound`.

**Comment by Alexander-Taran** [comment] 2018-03-18 23:46
not an issue.
discussion on future lifecycle

**Comment by EisenbergEffect** [comment] 2018-03-19 03:20
We've corrected this in our vNext prototype. In the new model, the change handlers are always called, regardless of whether or not there's a bind method. Additionally, the first time, all change handlers are called after all properties are set.

**Comment by Alexander-Taran** [comment] 2018-03-19 20:41
@EisenbergEffect if we don't need this as a reminder, can we close this?

**Comment by EisenbergEffect** [comment] 2018-03-19 20:53
Yes, we can close. It's fixed in the experiment repo :)

**Closed by EisenbergEffect** 2018-03-19 20:53 UTC
