### ISSUE TITLE
repeat.for not updating when using converters

### ISSUE THREAD

**Issue by bemon** [aurelia/templating#185] opened 2015-10-07 02:36 UTC
construction like this
```
<div repeat.for="item of object.someItems | filter: {type:5}">${item.name}</div>
```
is not  updating when add/remove items dynamically in object.someItems. Aurelia should bind to array as usual, then call converter function.

**Comment by jdanyow** [comment] 2015-10-30 21:11
duplicate of https://github.com/aurelia/binding/issues/183

**Closed by jdanyow** 2015-10-30 21:11 UTC
