### ISSUE TITLE
CompositionTransaction Bug (when using jquery autocomplete)

### ISSUE THREAD

**Issue by AdamWillden** [aurelia/templating#284] opened 2016-03-03 12:42 UTC
# Issue

I've found an issue which I believe to be created by the new CompositionTransaction.

Taken from my comments here: https://gitter.im/Aurelia/Discuss?at=56d82afaf760676329bb4648

> I have a strange issue with a jquery autocomplete since updating aurelia. I've reverted to just before the aurelia update and it works. I can see that the autocomplete is still instantiated properly but the suggestions box never shows.
>
> It's not just that it doesn't show, the autocomplete ul doens't appear in the DOM. I can see using chrome devtools that the <html> element flashes to suggest the the DOM has updated. I suspect the aurelia templating is removing it immediately after its has been added by jquery.

I've since noted that if I change pages (so that the router-view updates) the autocomplete element is suddenly added to the DOM and begins to operate as I expect. It's as if aurelia was restricting changes until the aurelia decided a DOM update was required (a transaction?).

I realise a live example would be useful but I've not got the time to create one and I suspect you will know if this is a likely scenario/bug.

# Scenario 1

1. Load Application
2. Do no navigate
3. Execute autocomplete search
4. nothing shows

# Scenario 2

1. Load Application
2. Immediately navigate
3. Execute autocomplete search
4. suggestion box shows

----
Moved from: https://github.com/aurelia/framework/issues/347

**Comment by EisenbergEffect** [comment] 2016-03-03 14:45
If you can create a small, simple reproduction of the bug, that would help us to fix it. Please base your repro off the skeleton and then just zip up and attach the src file to this issue. We can probably resolve this quickly if we have that in hand.

**Comment by AdamWillden** [comment] 2016-03-03 14:50
Okay I'll try and do that now.

**Comment by AdamWillden** [comment] 2016-03-03 16:06
See attached: [autocomplete-issue.zip](https://github.com/aurelia/templating/files/157137/autocomplete-issue.zip)

I have added an autocomplete containing 4 names (Adam, Ben, Carl, Dave) to the firstName input 

```js
<input type="text" value.bind="firstName" class="form-control" id="fn" placeholder="first name" autocomplete="source.bind: ['Adam', 'Ben', 'Carl', 'Dave'];">
```

It will not show until you navigate pages as described above.

**Comment by JeroenVinke** [comment] 2016-03-08 06:32
Seeing this with Kendo controls too (such as the datepicker)

**Comment by JeroenVinke** [comment] 2016-03-08 06:43
Reproduced here:

[datepicker.zip](https://github.com/aurelia/templating/files/162665/datepicker.zip)

Note that the are two datepickers, one in `welcome.html`  and one in `app.html`. Because the app.html does not change when navigating the datepicker popup in that one will never work. On initial load the datepicker popup in welcome.html does not work either, but after you navigate via the navbar it works

**Comment by AdamWillden** [comment] 2016-03-08 11:46
@JeroenVinke Thanks for adding your experience of this bug and your reproducible demo. I'm eagerly awaiting notifications regarding a fix!

**Comment by ralexand56** [comment] 2016-03-08 12:11
This makes the kendoui bridge unusable. Is there a suggested workaround?

**Comment by AdamWillden** [comment] 2016-03-08 15:55
@ralexand56 not that I know of. 

@EisenbergEffect is there a way to explicitly trigger a transaction that will allow us to work around the issue until this is fixed?

**Comment by JeroenVinke** [comment] 2016-03-08 16:02
@AdamWillden your sample works when `instantiate()` is called from `attached()` and not from `bind()`. Not sure if the same applies to Kendo controls (most of them are already initialized from `attached()`)

**Comment by AdamWillden** [comment] 2016-03-08 16:07
Ah right, thank you @JeroenVinke I didn't even notice I was doing instantiation on bind (which makes little sense). I'll test your theory.

**Comment by EisenbergEffect** [comment] 2016-03-08 19:11
I suspect that any jQuery-based controls will need to be invoked in the attached. Can anyone reproduce this issue without a 3rd party component library? I'm going to have to dig through Query and 3rd party component code to figure this out, which could take a while. If I had a repro without a 3rd party library, that would help this get resolved faster.

**Comment by EisenbergEffect** [comment] 2016-03-08 19:54
@AdamWillden This is how I would write your autocomplete

```
import {inject, customAttribute, dynamicOptions} from 'aurelia-framework';
import $ from 'jquery';
import 'jquery-ui/ui/autocomplete';
import 'jquery-ui/themes/smoothness/jquery-ui.css!';

@customAttribute('autocomplete')
@dynamicOptions
@inject(Element)
export class AutoComplete {
  constructor(element) {
    this.element = element;
    this.$element = $(element);
  }

  bind() {
    let defaultOptions = {
      source: this.source,
      minLength: this.minLength,
      select: this.select
    };

    this.options = Object.assign({}, defaultOptions);
  }
  
  attached() {
    this.$element.autocomplete(this.options);
  }

  detached() {
    this.$element.autocomplete('destroy').off('change');
  }

  propertyChanged(propertyName, newValue) {
    this.$element.autocomplete('option', propertyName, newValue);
  }
}
```

Something about the way `autocomplete` is implemented requires that it be called in `attached` after the component is actually attached to the document. I suspect this may be the case with any jQuery widget so this likely applies to Kendo as well. If things worked before it was probably due to a timing issue which was perhaps inconsistent.

I'm going to close this issue with this advice to move jQuery plugin invocation to the attached callback. If someone can find a way to reproduce this without a 3rd party widget, then please create a new issue with the offending sample so we can see if it's an issue with Aurelia.

**Closed by EisenbergEffect** 2016-03-08 19:54 UTC

**Comment by AdamWillden** [comment] 2016-03-09 10:54
@EisenbergEffect thanks for your help. I think we're all in agreement now.

Thanks also for the modified code. I had a `tabular-autocomplete` that inherited from that `autocomplete` but what you provided was a better structure and I managed to modify the `tabular-autocomplete` in the same fasion

**Comment by doktordirk** [comment] 2016-03-14 21:09
@JeroenVinke the 'aurelia-composed' event might be of use for you
