### ISSUE TITLE
created() callback never gets invoked

### ISSUE THREAD

**Issue by maca89** [aurelia/templating#241] opened 2016-01-02 17:45 UTC
Either I got it all wrong or there is a bug with created() callback. It never got invoked on any view-model. You can reproduce it on clean skeleton-navigation with only welcome.ts file changed – when you add bind and created methods, bind gets called as expected, while created never.

I need this callback to get hold of the view.

**Comment by danice** [comment] 2016-01-05 10:53
The same happens to me.

**Comment by EisenbergEffect** [comment] 2016-01-05 14:41
So, you are seeing this happen on the `welcome` view-model only, correct? If you create a custom element and use it inside the welcome view, you do see the `created` callback firing though, correct?

**Comment by danice** [comment] 2016-01-05 15:00
To me "create" is not called when using
```<compose view-model.bind="content"></compose>```
and loading content with
```this.content = "./init-toolbox";```
And also when the view is loaded by navigation.

**Comment by EisenbergEffect** [comment] 2016-01-05 15:03
Ok, yes. Create wouldn't be called for dynamic scenarios such as compose and router navigated screens. I believe that is an inconsistency that we need to fix. I will look into it.

**Comment by EisenbergEffect** [comment] 2016-01-05 20:36
I have a fix for this. I believe we can get it in to the next patch release, hopefully this week.

**Closed** 2016-01-08 22:24 UTC
Labels: bug

**Comment by danice** [comment] 2016-01-12 09:32
I think the issue is still open for view composition.

[Here](http://plnkr.co/edit/cUdgfBDT196XBDy1ZCkB?p=preview) is a plunker showing the issue.
What I'm trying is to some way to access parent properties from the child component.
