### ISSUE TITLE
string interpolation does not preserve class name ordering in template

### ISSUE THREAD

**Issue by tantommy** [aurelia/templating#373] opened 2016-06-05 21:20 UTC
When using string interpolation in a template for class, the evaluated expression does not preserve the order of classes in some cases.
```
//gives wrong ordering of classes
<div class="${data.length ? 'twelve wide column' : 'sixteen wide column'}"></div>

//also tried this with no luck
<div class="${data.length ? 'twelve' : 'sixteen'} wide column"></div>

//gives correct ordering of classes
<div class="${data.length ? 'a b c' : 'd e f'}"></div>
```
if !data.length, the result is:
```
//order of class names are not preserved
<div class="au-target wide column sixteen"></div>
```

Some style rules may depend on this order.

gist created:
https://gist.run/?id=fc23d1922cd6ea27e91ad804f2ade548

**Comment by jdanyow** [comment] 2016-06-07 12:29
https://github.com/aurelia/framework/issues/211

**Comment by EisenbergEffect** [comment] 2016-07-08 21:08
Closing as fixed dupe.

**Closed by EisenbergEffect** 2016-07-08 21:08 UTC

**Comment by mikeesouth** [comment] 2016-08-29 12:45
I'm still having this problem and I don't think it is the same problem as aurelia/framework#211. When using the code from @tantommy I get the correct order the first time (twelve wide column) but when I change data.length and Aurelia rebinds the classes it keeps "wide column", removes "twelve" and adds "sixteen" resulting in the order (wide column sixteen).
Did you solve the problem @tantommy?

**Comment by jdanyow** [comment] 2016-08-29 12:59
@mikeesouth please setup a reproduction and we'll take a look: https://gist.run/?id=7542e061bc940cde506b

**Comment by mikeesouth** [comment] 2016-08-29 13:09
@jdanyow the gist from @tantommy still works: https://gist.run/?id=fc23d1922cd6ea27e91ad804f2ade548
When you click the "click me" texts the items.length changes and thus triggers some databindings. When looking at div A, this databinding is used:
`"${items.length ? 'twelve wide column' : 'sixteen wide column'}"`
The expected result is `sixteen wide column` but the result is `wide column sixteen`.

**Comment by jdanyow** [comment] 2016-08-29 13:22
ah- because it's you're really only adding one class.  The logic isn't that smart. Either do this:
```html
<div class="${data.length ? 'twelve' : 'sixteen'} wide column"></div>
```
or this:
```html
<div class-name="${data.length ? 'twelve wide column' : 'sixteen wide column'}"></div>
```

that latter is the most performant

**Comment by mikeesouth** [comment] 2016-08-29 13:31
@jdanyow ah, the first one doesn't work. It yields the same result as the first. However, the second approach (class-name) does indeed work. Thanks! Where can I find more documentation on this "-name" syntax?

**Comment by jdanyow** [comment] 2016-08-29 13:40
The DOM is case insensitive, when it parses your markup, everything ends up being lowercase.  This makes it hard to bind to element properties like [`className`](https://developer.mozilla.org/en-US/docs/Web/API/Element/className).  Aurelia's solution is to use a convention where hyphenated names in your template are converted to camelCase.

So `class-name="${...}"` or `class-name.bind="..."` is going to assign the DOM element's [`className`](https://developer.mozilla.org/en-US/docs/Web/API/Element/className) property. 

By assigning the property directly, you're skipping all the logic we have around making sure we don't stomp on existing classes, etc. Binding className in this way will wipe out whatever is in the element's class list and replace it with the result of your binding which is the expected result in 99% of the use cases.

**Comment by mikeesouth** [comment] 2016-08-29 13:44
Great explanation. Thanks!
